info:
  appName: ${spring.application.name}
  appDesc: 'Sancho Application Test'
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
  license: GPL2
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8080
  servlet:
    context-path:
